### ISSUE TITLE
Question about VLS

### ISSUE THREAD

**Issue by Lukas-Ma1** [CUHK-AIM-Group/CLIFF#5]
Hi there! I read your CLIFF and got deeply impressed about what you've done in combining diffusion and ovod. Still, I have question about your proposed VLS.

I understand you introduce x_obj to generate initial noise (x_T), which can give prior knowledge to reverse noise process. However, the objective function of VLS is to optimize the initial noise generation `p(x_T | x_obj)` to Standard Gaussian distribution N(0,1). 
Does this approach mean the best form of `p(x_T | x_obj)` equals N(0,1)? If this case, why don't you directly use N(0,1) to generate x_T? Although that approach will be the same as DDPM's, I got confusion about your design of VLS's objective function.

**Comment by wymanCV** [comment]
Hi, sorry for the late reply. Thank you so much for your interest in our work! Great question!!

Yes, both `p(x_T | x_obj)` and `p(x_T)` satisfy the same numerical distribution with N(0,1), but they represent different latent spaces. Note that `p(x_T)` is entirely random without semantic information, while `p(x_T | x_obj)` is semantically aware. 

To clarify, consider a scenario where VAE latents [1] are used for classification: In a VAE, it is common to add a classifier to the learned latent distribution p(z|x) for classification purposes, even though p(z|x) is constrained to N(0,1) via the KL loss. Clearly, it is impossible to add a meaningful classifier to pure noise p(z), despite both distributions being normally distributed. The reason lies in that the discriminability is hidden in the pattern of feature vectors, instead of the numerical distribution. Thus, This key difference between  `p(x_T | x_obj)` and `p(x_T)` is what motivates the design of VLS. I hope this helps! 



[1] [Auto-Encoding Variational Bayes](https://arxiv.org/abs/1312.6114)

Best,
Wuyang
